baseURL = "https://www.dachengply.com/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "DaChengPly"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "Fubukii"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "About us"
    url        = "/"
    weight     = 1
    parent     = "menu.home"

[[menu.main]]
    name       = "Customers"
    url        = "/"
    weight     = 2
    parent     = "menu.home"

[[menu.main]]
    name       = "Partners"
    url        = "/"
    weight     = 3
    parent     = "menu.home"

[[menu.main]]
    name       = "Furniture"
    identifier = "menu.Furniture"
    url        = "/img/shoecabinet.jpg"
    weight     = 2

[[menu.main]]
    name       = "Furniture by use"
    identifier = "section.Furniture by use"
    url        = ""
    weight     = 1
    parent     = "menu.Furniture"
    post       = 1

[[menu.main]]
    name       = "Cabinets & Tables"
    identifier = "section.Cabinets&Tables"
    url        = ""
    weight     = 2
    parent     = "menu.Furniture"
    post       = 2

[[menu.main]]
    name       = "Bookcase/storage"
    url        = ""
    weight     = 1
    parent     = "section.Furniture by use"

[[menu.main]]
    name       = "Shoe Cabinet"
    url        = ""
    weight     = 2
    parent     = "section.Furniture by use"

[[menu.main]]
    name       = "Side Table/Bar"
    url        = ""
    weight     = 3
    parent     = "section.Furniture by use"

[[menu.main]]
    name       = "Office Desk"
    url        = ""
    weight     = 4
    parent     = "section.Furniture by use"

[[menu.main]]
    name       = "Living room cabinets"
    url        = ""
    weight     = 5
    parent     = "section.Furniture by use"

[[menu.main]]
    name       = "Bathroom cabinets"
    url        = ""
    weight     = 6
    parent     = "section.Furniture by use"

[[menu.main]]
    name       = "Kitchen cabinets"
    url        = ""
    weight     = 7
    parent     = "section.Furniture by use"

[[menu.main]]
    name       = "Wardrobe"
    url        = ""
    weight     = 8
    parent     = "section.Furniture by use"

[[menu.main]]
    name       = "Bookcase"
    url        = ""
    weight     = 1
    parent     = "section.Cabinets&Tables"

[[menu.main]]
    name       = "Shoe Cabinet"
    url        = ""
    weight     = 2
    parent     = "section.Cabinets&Tables"

[[menu.main]]
    name       = "Office desk"
    url        = ""
    weight     = 3
    parent     = "section.Cabinets&Tables"

[[menu.main]]
    name       = "Building Materials"
    identifier = "menu.Building Materials"
    url        = "/img/buildingmaterials.jpg"
    weight     = 3

[[menu.main]]
    name       = "MDF"
    identifier = "section.MDF"
    url        = ""
    weight     = 1
    parent     = "menu.Building Materials"
    post       = 1

[[menu.main]]
    name       = "Plain MDF"
    url        = "/blog/"
    weight     = 1
    parent     = "section.MDF"

[[menu.main]]
    name       = "Melamine MDF"
    url        = ""
    weight     = 2
    parent     = "section.MDF"

[[menu.main]]
    name       = "VENEER MDF"
    url        = ""
    weight     = 3
    parent     = "section.MDF"

[[menu.main]]
    name       = "Melamine Slotted MDF"
    url        = ""
    weight     = 4
    parent     = "section.MDF"

[[menu.main]]
    name       = "Wood Veneer"
    identifier = "section.Venner"
    url        = ""
    weight     = 2
    parent     = "menu.Building Materials"
    post       = 1

[[menu.main]]
    name       = "Nature Veneer"
    url        = ""
    weight     = 1
    parent     = "section.Venner"

[[menu.main]]
    name       = "Engineered Veneer"
    url        = ""
    weight     = 2
    parent     = "section.Venner"

[[menu.main]]
    name       = "Building Materials - detail"
    url        = ""
    weight     = 3
    parent     = "section.Venner"

[[menu.main]]
    name       = "Plywood"
    identifier = "section.plywood"
    url        = ""
    weight     = 2
    parent     = "menu.Building Materials"
    post       = 2

[[menu.main]]
    name       = "Melamine Plywood"
    url        = ""
    weight     = 1
    parent     = "section.plywood"

[[menu.main]]
    name       = "Flim faced plywood/Marine plywood"
    url        = ""
    weight     = 2
    parent     = "section.plywood"

[[menu.main]]
    name       = "Commercial plywood"
    url        = ""
    weight     = 3
    parent     = "section.plywood"

[[menu.main]]
    name       = "Fancy plywood"
    url        = ""
    weight     = 4
    parent     = "section.plywood"  

[[menu.main]]
    name       = "Other"
    identifier = "section.other"
    url        = ""
    weight     = 3
    parent     = "menu.Building Materials"
    post       = 2

[[menu.main]]
    name       = "Particle Board"
    url        = ""
    weight     = 1
    parent     = "section.other"

[[menu.main]]
    name       = "Pvc Edge Banding"
    url        = ""
    weight     = 1
    parent     = "section.other"

#[[menu.main]]
#    name       = "All Pages"
#    identifier = "menu.allpages"
#    url        = ""
#    weight     = 4
#
# [[menu.main]]
#     name       = "Home"
#     identifier = "section.ap-home"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 1

# [[menu.main]]
#     name       = "About"
#     identifier = "section.ap-plywood"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 1

# [[menu.main]]
#     name       = "Marketing"
#     identifier = "section.ap-marketing"
#     url        = ""
#     weight     = 3
#     parent     = "menu.allpages"
#     post       = 1

# [[menu.main]]
#     name       = "Building Materials"
#     identifier = "section.ap-Building Materials"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 2

# [[menu.main]]
#     name       = "User Pages"
#     identifier = "section.ap-userpages"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 2

# [[menu.main]]
#     name       = "Shop"
#     identifier = "section.ap-shop"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 3

# [[menu.main]]
#     name       = "Shop - Order Process"
#     identifier = "section.ap-shoporderprocess"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 3

# [[menu.main]]
#     name       = "Contact"
#     identifier = "section.ap-contact"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 4

# [[menu.main]]
#     name       = "Pages"
#     identifier = "section.ap-pages"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 4

# [[menu.main]]
#     name       = "blog"
#     identifier = "section.ap-blog"
#     url        = "/blog/"
#     weight     = 3
#     parent     = "menu.allpages"
#     post       = 4

# [[menu.main]]
#     name       = "blog Listing Big"
#     url        = "/blog/"
#     weight     = 1
#     parent     = "section.ap-blog"

# [[menu.main]]
#     name       = "blog"
#     identifier = "menu.blog"
#     url        = "/blog/"
#     weight     = 5

# [[menu.main]]
#     name       = "FAQ"
#     identifier = "menu.faq"
#     url        = "/faq/"
#     weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+86 135 8329 681034 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:505723147@qq.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Fubuki"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Qingdao Dacheng International Trading Company was established in 2016. Product range includes plywood, MDF Board, Particle Board, bookcases and shoe cabinets etc., supporting OEM and ODM. Our strength lies in our cooperation with many manufacturing companies, which are densely located in Shandong, China.</p>"
    copyright = "Copyright © Qingdao Dacheng International Trade Co., Ltd.; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "DaChengPly"

    logo = "img/logo-plymdale483.png"
    logo_small = "img/logo-small-plymdale.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>DaChengPly</strong>
        <br>Fengtai Street Office 
        <br>Pingdu
        <br>Qingdao
        <br>Shandong
        <br>
        <strong>China</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +86 135 832 96810 or 505723147@qq.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+86 135 8329 6810" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:505723147@qq.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.Furniture]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All Furniture are defined in their own files. You can find example items
    # at 'exampleSite/data/Furniture'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said plywood us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
